name: Build RPS Game

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller --windowed --onedir --name "RPS" RPS.py
            mkdir -p dist-macos
            cp -r dist/RPS.app dist-macos/
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --windowed --name "RPS" RPS.py
          else
            pyinstaller --onefile --name "RPS" RPS.py
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: RPS-${{ matrix.os }}
          path: |
            dist/*
            dist-macos/*
